GET localhost:8080/api/v1/product/910/detail
Content-Type: application/json
###

GET localhost:8080/api/v1/product/promotion?offsetId=2&size=100&orderBy=ID
Content-Type: application/json
###

GET localhost:8080/api/v1/product/search?keyword=라면&offsetProductId=6222
Content-Type: application/json

###
GET localhost:8080/api/v1/product/search
Content-Type: application/json


###
POST localhost:8080/api/v1/product/908/rate/like
###
GET localhost:8080/temp
